<?php
/*  

Ajusta los textos de acuerdo a tu idioma


*/
$langextra = array(
'SUPER_ADMIN' => 'SUPER_ADMIN',
'GERENTE' => 'GERENTE',
'ASISTENTE' => 'ASISTENTE',
'JEFE DE TALLER' => 'JEFE DE TALLER',
'VALUADOR' => 'VALUADOR',
'ASESOR' => 'ASESOR',
'JEFE DE AREA' => 'JEFE DE AREA',
'ALMACEN' => 'GESTION DE REFACCIONES',
'OPERADOR' => 'OPERADOR',
'AUXILIAR' => 'AUXILIAR',
'VIGILANCIA' => 'VIGILANCIA',
'CALIDAD' => 'CALIDAD',
'COBRANZA' => 'COBRANZA',
'PAGOS' => 'PAGOS',
'ASEGURADORA' => 'ASEGURADORA',
);
