<?php
/*  

Ajusta los textos de acuerdo a tu idioma


*/
$titulo="Terminado y Entrega de Ordenes de Trabajo | AutoShop Easy";
$keywords="administración de taller, control de taller";
$pag_desc="AutoShop Easy: Aplicación para administración de todas las etapas del proceso de un Taller Mecánico Clase Mundial.";
$pagina_actual="Terminado y Entrega de Ordenes de Trabajo";

define('EMAIL_ENTREGA_ASUNTO', 'Su Automóvil está listo.');
define('EMAIL_ENTREGA_SALUDO', 'Estimad@ ');
define('EMAIL_ENTREGA_CONT1', 'De acuerdo a nuestra conversación de hace algunos minutos, le confirmamos que estamos concluyendo las tareas programadas en la Orden de Trabajo ');
define('EMAIL_ENTREGA_CONT2', 'realizadas al vehículo');
define('EMAIL_ENTREGA_CONT3', 'La fecha y hora de entrega de su vehículo acordada con Usted fue el ');
define('EMAIL_ENTREGA_CONT4', ' con un costo de ');
define('EMAIL_ENTREGA_CONT5', 'Reciba un cordial saludo.');  /*  Proceso administrado por AutoShop-Easy.com */
define('EMAIL_ENTREGA_MONEDA', ' pesos.');
// define('', '');

$lang = array(
'Acceso a Asesor' => 'Acceso autorizado a Asesor',
'Acceso a Calidad' => 'Acceso autorizado a Calidad',
'Acceso a Jefe de Area' => 'Acceso autorizado a Jefe de Area',
'Acceso a Supervisor' => 'Acceso autorizado a Supervisor',
'Acceso autorizado' => 'Acceso autorizado',
'Acceso no autorizado' => 'Acceso no autorizado, ingresar Usuario y Clave correcta',
'Acceso para Asesor de Servicio' => 'Acceso sólo para Asesor de Servicio, ingresar Usuario y Clave correcta',
'Acceso para Gerentes' => 'Acceso sólo para Gerentes, ingresar Usuario y Clave correcta',
'agregue un comentario' => 'Opcionalmente agregue un comentario<br>para la próxima llamada al cliente: ',
'Anticipo' => 'Anticipo',
'Apellidos' => 'Apellidos',
'APROBAR' => 'APROBAR',
'Archivo XML' => 'Archivo XML',
'aseguradora' => ' a la aseguradora ',
'Asignar al preparador' => 'Asignar al preparador: ',
'Banco Origen' => 'Banco Origen',
'Banco y Cuenta de cobro' => 'Debe indicar Banco origen y Cuenta de cobro para la forma de cobro elegida.',
'Borrar' => 'Cancelar Factura',
'Borrar Factura' => '¿Desea cancelar la Factura? Por favor marque la casilla ->',
'Cant' => 'Cant',
'Cantidad' => 'Cantidad',
'Captura de NC Gen' => 'Captura de Nota de Crédito como descuento General',
'cliente' => ' al cliente ',
'Cliente' => 'Cliente: ',
'Cobro de factura ' => 'Cobro de factura ',
'cobro de la factura' => ' del cobro de la factura ',
'Cobro Total' => 'Cobro Total de ',
'Código' => 'Código: ',
'Color' => 'Color',
'Comentarios' => 'Comentarios: ',
'Comprobante Simplificado' => 'Remisión',
'Comprob Cobro de factu' => 'Comprobante de Cobro de factura ',
'Conceptos a cobrar' => 'Conceptos a cobrar para ',
'Conceptos de Facturación' => 'Conceptos de Facturación',
'Concepto de la NC' => 'Concepto de la Nota de Crédito',
'Concepto vacio' => 'Por favor capture el concepto para la Nota de Crédito.',
'confirme la entrega del vehículo' => 'Por favor confirme la entrega del vehículo!',
'Consumibles' => 'Consumibles',
'Cuenta de Cobro' => 'Cuenta de Depósito',
'Datos del Cliente' => 'Datos del Cliente',
'Datos del Vehiculo' => 'Datos del Vehículo',
'Datos incompletos' => 'Datos incompletos, por favor regrese al cobro.',
'Deducible' => 'Deducible',
'del Siniestro' => ' del Siniestro: ',
'Descripción' => 'Descripción',
'Descripción de la Tarea' => '. Descripción de la Tarea: ',
'Documento' => 'Documento',
'Emisión de factura' => 'Emisión de Factura ',
'Emisión del Comprobante Simplificado' => 'Emisión de Remisión ',
'Emitida el' => ' Emitida el ',
'Entregado - Cerrado' => 'Entregado - Cerrado',
'Enviar' => 'Enviar',
'Enviar a Aseguradora' => '¿Desea enviar el archivo de cierre a la Aseguradora?',
'Factura externa XML CFDi' => 'Documento externo: Agregue el archivo XML CFDi de Factura o Remisión',
'Factura' => 'Factura',
'factura por cobrar eliminada' => 'Se canceló la factura por cobrar ',
'Fecha acordada con el Cliente' => 'Fecha acordada con el Cliente para su entrega: ',
'Fecha Cliente recibió' => 'Fecha en que el Cliente recibió ',
'Fecha de emisión' => 'Fecha de emisión',
'Fecha del cobro' => 'Fecha del cobro',
'Fecha' => 'Fecha',
'Fecha llamada al cliente' => 'Fecha estimada para próxima llamada al cliente: ',
'Fecha programada de pago' => 'Fecha programada de pago de ',
'Fecha y Hora para la entrega del vehículo' => 'Seleccione una Fecha y Hora para la entrega del vehículo.',
'Forma de cobro' => 'Forma de cobro',
'fue eliminada' => ' fue cancelada!',
'Gran Total' => 'Gran Total: ',
'Hora acordada con el Cliente' => 'Hora acordada con el Cliente para su entrega: ',
'Imagen de comprobante de cobro' => 'Imagen de comprobante de cobro: ',
'Archivo comprobante de entrega' => 'Agregar archivo que compruebe que el vehículo fue entregado al Cliente',
'impor tot de fact no coinc con tot a cobr' => 'El importe total de la factura no coincide con el total a cobrar.',
'Importe de la NC' => 'Importe SIN impuestos',
'Importe NC no menor' => 'El importe de la Nota de Crédito no puede ser menor a 1 peso.',
'Imprimir Conceptos de Factura' => 'Imprimir Conceptos de Factura',
'Imprimir Deducible' => 'Imprimir Carta de Deducible',
'Imprimir Garantía' => 'Imprimir Garantía de Reparación',
'Ingreso por Materi de la factura' => 'Ingresos por Materiales de la factura ',
'Ingreso por Refacc de la factura' => 'Ingresos por Refacciones de la factura ',
'Ingreso por servic de Hojal, Mec de la factura' => 'Ingresos por servicios de Hojalatería, Mecánica y Otros de la factura ',
'Ingreso por servic de Pintu de la factura' => 'Ingresos por servicios de Pintura de la factura ',
'intente de nuevo' => ', intente de nuevo.',
'IVA cobrado de la factura' => 'IVA cobrado de la factura ',
'IVA' => 'IVA:',
'IVA Trasladado por cobrar de factura' => 'IVA Trasladado por cobrar de factura ',
'La factura' => 'La factura ',
'Limpiar Selección' => 'Limpiar Seleciones',
'Mano de Obra' => 'Mano de Obra',
'Marca' => 'Marca',
'más de un siniestro o tipo de servicio, elija el reporte' => 'Existe más de un siniestro o tipo de servicio que se puede entregar, elija el reporte adecuado:	',
'Método de Cobro' => 'Método de Cobro',
'Modelo' => 'Modelo',
'Monto Cobrado' => 'Monto Cobrado',
'Monto Deducible' => 'Monto Deducible',
'Monto de este cobro' => 'Monto de este cobro',
'Monto del cobro no debe ser superior' => 'El monto del cobro no puede ser superior al monto pendiente por cobrar.',
'monto del cobro no puede ser cero' => 'El monto del cobro no puede ser cero, negativo o vacío.',
'Movil 1' => 'Movil 1: ',
'Movil 2' => 'Movil 2: ',
'Nada' => '',
'No agregado Hoja de Daños' => 'No se ha agregado la Hoja de Daños.',
'No agregado Orden de Admisión' => 'No se ha agregado la Orden de Admisión.',
'No agregó imagen de comprobante de entrega' => 'No se agregó imagen de comprobante de entrega.',
'no está esperando evaluación' => 'Esta actividad no está esperando evaluación!',
'No hay foto de VIN' => 'No se agregó foto de VIN.',
'No hay fotos de ingreso' => 'No se han agregado suficientes fotos de ingreso.',
'No hay montos de valuación' => 'No hay montos de valuación, no se puede dar por terminada.',
'No hay registros con esos datos' => 'No se encontraron registros con esos datos.',
'No hubo selección válida' => 'No hubo selección válida',
'Nombre' => 'Nombre',
'No se cerró la orden de trabajo' => 'No se cerró la orden de trabajo ',
'No se liberó el automovil de la OT' => 'No se liberó el automovil de la Orden de Trabajo ',
'No se localizó la OT o El Cliente o el Vehículo indicado' => 'No se localizó la Orden de Trabajo o El Cliente o el Vehículo indicado',
'No se marcó como entregado el vehículo de la OT' => 'No se marcó como entregado el vehículo de la OT ',
'no tiene tareas no registra cobros' => 'La OT no tiene tareas: no se pueden registrar cobros.',
'Comprobante de entrega' => 'Comprobante de entrega',
'Notificacion Automatica' => 'Notificacion Automatica de ',
'no válida la SOT' => 'No se encontró o no es válida la Tarea ',
'Num cheque o transferencia' => 'Indique el número de cheque o transferencia.',
'Num Cobro' => 'Numero de Cobro',
'número de recibo de Deducible' => 'Captura de número de recibo de Deducible',
'Número de Recibo' => 'Número de Recibo',
'ot-cerrada' => 'ot-cerrada',
'OT' => ' de la OT ',
'OT no terminada no registrar cobros' => 'La OT no está terminada: no se pueden registrar cobros todavía',
'para su entrega' => '  para su entrega.',
'Pasar código de barras de SOT presiona Enter' => 'Pasa el código de barras de la SOT por el lector o escribe el código en el siguiente campo y después presiona Enter',
'Placas' => ' Placas: ',
' Placas: ' => ' Placas: ',
'PLACAS' => 'PLACAS',
'Por cobrar' => 'Por cobrar:',
'por un total de' => ' por un total de ',
'Precio' => 'Precio',
'Precio Unitario' => 'Precio Unitario',
'Preparación de Automóvil para entrega a cliente' => 'Preparación de Automóvil para entrega a cliente',
'programada para cobro' => ' programada para cobro el ',
'Refacciones' => 'Refacciones',
'Referencia' => 'Referencia',
'Regist fecha programada de pago' => 'Registrar recepción y fecha programada de pago de ',
'Registrar cobro' => 'Registrar cobro de ',
'Registra recibo y fecha de pago de Factura' => 'Registrar recibo y fecha programada de pago de Factura',
'Registrar Factura' => 'Registrar Factura o Remisión',
'Registrar recibo de Deducible' => 'Registrar recibo de Deducible',
'Registro de Cobros' => 'Registro de Cobros para las Tareas ',
'Registro de recepción' => 'Registro de recepción de ',
'Registro de Recepción' => 'Registro de Recepción de ',
'Registro de' => 'Registro de ',
'Registro en cuenta' => 'Registro en cuenta ',
'Regresar a cobros' => 'Regresar a cobros',
'Regresar a la OT' => 'Regresar a la Orden de Trabajo',
'REPROCESAR' => 'REPROCESAR',
'Resumen de Tareas por Cobrar' => 'Resumen de Tareas por Cobrar',
'Selecc forma de pago' => 'Seleccione una forma de pago.',
'Seleccione' => 'Seleccione...',
' Seleccione... ' => ' Seleccione... ',
'Seleccione Area' => 'Seleccione el área de servicio',
'Seleccione un Lavador' => 'Seleccione un Lavador:',
'Serie' => 'Serie',
'siniestro' => ' del siniestro ',
'Subtotal' => 'Subtotal: ',
'Sub Total' => 'Sub Total',
'Tarea a Evaluar' => 'Selecciona la Tarea a Evaluar',
'Tareas del área' => 'Tareas del área ',
'Tareas ejecutadas en la OT' => 'Tareas ejecutadas en la Orden de Trabajo ',
'Tarea para NC' => 'Se agregó tarea para registro de Nota de Crédito',
'Teléfono 1' => 'Teléfono 1: ',
'Teléfono 2' => 'Teléfono 2: ',
'Tipo' => 'Sub marca',
'Total de suborden' => 'Total de suborden: ',
'Total' => 'Total:',
'Total Neto a Cobrar' => 'Total Neto a Cobrar con Impuestos incluidos: ',
'Diferencia por Ajustar' => 'Aplicar ajuste por diferencia de:',
'' => '',
'' => '',
'' => '',
'' => '',
'' => '',
'' => '',
'' => '',
'' => '',
'' => '',
'' => '',
);

if(file_exists('particular/textos/variantes.php')) {
	include('particular/textos/variantes.php');
	$lang = array_replace($lang, $langextra);
}


/* Página de idiomas para entrega */ 
